http:
  routers:
    api:
      rule: "Host(`api.localhost`)"
      service: api
      entryPoints:
        - web
    frontend:
      rule: "Host(`localhost`)"
      service: frontend
      entryPoints:
        - web

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:8000"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
