/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanBomIdRouteImport } from './routes/scan.$bomId'
import { Route as AdminMlRouteImport } from './routes/admin.ml'

const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanBomIdRoute = ScanBomIdRouteImport.update({
  id: '/scan/$bomId',
  path: '/scan/$bomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMlRoute = AdminMlRouteImport.update({
  id: '/admin/ml',
  path: '/admin/ml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/admin/ml': typeof AdminMlRoute
  '/scan/$bomId': typeof ScanBomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/admin/ml': typeof AdminMlRoute
  '/scan/$bomId': typeof ScanBomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/admin/ml': typeof AdminMlRoute
  '/scan/$bomId': typeof ScanBomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ask' | '/admin/ml' | '/scan/$bomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ask' | '/admin/ml' | '/scan/$bomId'
  id: '__root__' | '/' | '/ask' | '/admin/ml' | '/scan/$bomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AdminMlRoute: typeof AdminMlRoute
  ScanBomIdRoute: typeof ScanBomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$bomId': {
      id: '/scan/$bomId'
      path: '/scan/$bomId'
      fullPath: '/scan/$bomId'
      preLoaderRoute: typeof ScanBomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ml': {
      id: '/admin/ml'
      path: '/admin/ml'
      fullPath: '/admin/ml'
      preLoaderRoute: typeof AdminMlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AdminMlRoute: AdminMlRoute,
  ScanBomIdRoute: ScanBomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
